### ISSUE TITLE
'_InterlockedIncrement64': identifier not found

### ISSUE THREAD

**Issue by rcmpayne** [exaphaser/libimobiledevice-win64#1]
Getting the following when building on VS2015

Severity	Code	Description	Project	File	Line	Suppression State
Error	C3861	'_InterlockedIncrement64': identifier not found	libimobiledevice	c:\program files (x86)\windows kits\8.1\include\um\winbase.h	8848

**Comment by 0xFireball** [comment]
Hello!
If you look at the error, it's in `winbase.h` in a Windows kit...
I've never tried building this on Windows 8.1; try on Windows 10 64-bit. You will also probably need the Win10 SDK/headers...

**Comment by rcmpayne** [comment]
perfect, thanks
